database:
  db_type: "mysql"
  db_address: "127.0.0.1"
  db_name: "nepcatdata"
  db_user: "root"
  db_password: "cx030115"
  port: 3306

logging:
  log_level: "info"
  log_dir: "/var/log/myapp"

server:
  http_enabled: true
  http_port: 8443
  https_enabled: true
  https_port: 8000
  rpcserver: 192.168.8.20:50000

nepcatinfo:
  localaddress: "127.0.0.1@"
  port: 3000

websocket:
  host: "127.0.0.1"
  port: 3001
  scheme: "ws"
  path: "/"
  rawquery: "access_token="
mode:
  replymode: "全回复"
adminuser:
  acount:
    - "admin"
    - "root"
    - "cx"
#  包含全回复，部分回复，管理员回复，开发者回复四种模式
