package Const

const (
	VRTS_COMMAND_TYPE_HEARTBEAT = 1
	VRTS_COMMAND_RESP_MASK      = 2
	VRTS_COMMNAND_TYPE_CALL     = 3
	VRTS_COMANND_TYPE_REGIST    = 4
)

const (
	VRTS_SERVER_TYPE_NEPCAT    = 10001
	VRTS_SERVER_TYPE_WEBSERVER = 10002
)
