package Const

const (
	VRTS_COMMAND_TYPE_HEARTBEAT = 1 //心跳
	VRTS_COMMAND_RESP_MASK      = 2 //响应
	VRTS_COMMNAND_TYPE_CALL     = 3 //调用
	VRTS_COMANND_TYPE_REGIST    = 4 //注册
)

const (
	VRTS_SERVER_TYPE_NEPCAT    = 10001
	VRTS_SERVER_TYPE_WEBSERVER = 10002
)
